---
- name: install mongodb
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - mongodb
    - mongodb-server

- name: configure dbdir
  file:
    path: '{{ mongo_db_path }}'
    owner: mongodb
    group: mongodb
    state: directory

- name: tunning sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  with_items:
    - { name: "vm.dirty_ratio", value: "15" }
    - { name: "vm.dirty_background_ratio", value: "5" }
    - { name: "vm.swappiness", value: "1" }
    - { name: "net.core.somaxconn", value: "4096" }
    - { name: "net.ipv4.tcp_fin_timeout", value: "30" }
    - { name: "net.ipv4.tcp_keepalive_intvl", value: "30" }
    - { name: "net.ipv4.tcp_keepalive_time", value: "120" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "4096" }

- name: save sysctl config
  command: sysctl -p
  ignore_erros: yes

- name: limits to mongodb
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: '{{ item }}'
  with_items:
    - "mongod soft nproc 64000"
    - "mongod hard nproc 64000"
    - "mongod soft nofile 64000"
    - "mongod hard nofile 64000"

- name: configure mongodb dir
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongodb
    group: mongodb

- name: start and enable mongodb service
  systemd:
    name: mongod
    state: started
    enabled: yes
