- hosts: all
  become: yes
  become_method: sudo
  vars:
    - machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
  tasks:
    - debug:
        msg: "My pass: {{ password }} My user: {{ username }}"
 

