---
- name: Hello World!
  hosts: all
  vars:
    foo: foo
    lala: lala
  tasks:
 
  - name: Check SSH
    shell: "echo Hello World"

  - name: Sleep to test running parallel jobs.
    wait_for: timeout=300

  - name: Hello World!
    debug: 
      msg: 'Hello World!!! Server {{ ansible_hostname }} var foo={{ foo }} var lala={{ lala }}'
