---
- name: Hello World!
  hosts: all
#  vars:
#    foo: foo
#    lala: lala
  tasks:
 
  - name: Check SSH
    shell: "echo Hello World"

  - name: Hello World!
    debug: 
      msg: "Hello World!!! Server {{ ansible_hostname }} var foo={{ foo }} var lala={{ lala }}"
