---
- name: all playbook
  hosts: all
  vars:
    data_raw_size: "20.00 GB"
    arch_raw_size: "20.00 GB"
  tasks:

  - set_fact: 
      disks: "{{ ansible_devices.keys() | list }}"

  - set_fact:
      usable_disks: "{{ disks |select('match', '^(s|v)d+') | list }}"

  - set_fact: 
      data_raw_disk_name: "{{ item }}"
    when: 
      - "ansible_devices.{{ item }}.partitions.keys() |list | length <= 0"
      - ansible_devices.{{ item }}.size == "{{ data_raw_size }}"
    with_items:
      - "{{ usable_disks }}"

  - parted:
      device: "/dev/{{ data_raw_disk_name }}"
      number: 1
      state: present
      part_end: 25%

  - parted:
      device: "/dev/{{ data_raw_disk_name }}"
      number: 2
      state: present
      part_start: 25%
      part_end: 50%

  - parted:
      device: "/dev/{{ data_raw_disk_name }}"
      number: 3
      state: present
      part_start: 50%
      part_end: 75%

  - parted:
      device: "/dev/{{ data_raw_disk_name }}"
      number: 4
      state: present
      part_start: 75%
      part_end: 100%

  - name: Collect only facts returned by facter
    setup:

  - set_fact: 
      arch_raw_disk_name: "{{ item }}"
    when: 
      - "ansible_devices.{{ item }}.partitions.keys() |list | length <= 0"
      - ansible_devices.{{ item }}.size == "{{ arch_raw_size }}"
    with_items:
      - "{{ usable_disks }}"

  - parted:
      device: "/dev/{{ arch_raw_disk_name }}"
      number: 1
      state: present
      part_end: 25%

  - parted:
      device: "/dev/{{ arch_raw_disk_name }}"
      number: 2
      state: present
      part_start: 25%
      part_end: 50%

  - parted:
      device: "/dev/{{ arch_raw_disk_name }}"
      number: 3
      state: present
      part_start: 50%
      part_end: 75%

  - parted:
      device: "/dev/{{ arch_raw_disk_name }}"
      number: 4
      state: present
      part_start: 75%
      part_end: 100%
