---
- name: Playbook Add new host in same playbook
  hosts: all
  vars:
    foo: foo
    lala: lala
  tasks:
 
  - name: Check SSH
    shell: "echo Hello World"

  - name: Hello World!
    debug: 
      msg: 'Hello World!!! Server {{ ansible_hostname }}'

  - name: Create new vm host group and add host
    add_host:
      name: "client01"

  - name: Check SSH
    shell: "echo Hello World"
    delegate_to: '{{ name }}'

  - name: Hello World!
    debug: 
      msg: 'Hello World!!! Server {{ ansible_hostname }}'
    delegate_to: '{{ name }}'
