- name: Criar VG
  lvg: vg={{ create_vgname }} pvs={{ new_disk }} state=present
- name: Criar LV
  lvol: vg={{ create_vgname }} lv={{ create_lvname }} size={{ create_lvsize }}
- name: Criar o FS no LV
  filesystem: fstype={{ filesystem }} dev=/dev/{{ create_vgname }}/{{ create_lvname }}
- name: Montar o FS
  mount: name={{ new_mntp }} src=/dev/{{ create_vgname }}/{{ create_lvname }} fstype={{ filesystem }} 
