---
- uri:
    url: http://ansible.acme.local:81/index.json
    return_content: yes
  register: json

- name: get dns server location for devel
  set_fact:
    ipaddr1: "{{ json.content | from_json |json_query('IP_Maquina[0]') }}"
    ipaddr2: "{{ json.content | from_json |json_query('IP_Branca[0]') }}"
    ipaddr3: "{{ json.content | from_json |json_query('IP_Backup[0]') }}"
    network1: "{{ json.content | from_json |json_query('L2') }}"
    network2: "{{ json.content | from_json |json_query('L3_Branca') }}"
    network3: "{{ json.content | from_json |json_query('L3_Backup') }}"
    netmask1: '255.255.255.0'
    netmask2: '255.255.255.0'
    netmask3: '255.255.255.0'

- name: set gateway
  set_fact:
    gateway: "{{ ipaddr1.split('.')[0] }}.{{ ipaddr1.split('.')[1] }}.{{ ipaddr1.split('.')[2] }}.1"

- name: debug json
  debug:
    var: ipaddr1

- name: debug json
  debug:
    var: ipaddr2

- name: debug json
  debug:
    var: ipaddr3

- name: debug json
  debug:
    var: network1 

- name: debug json
  debug:
    var: network2 

- name: debug json
  debug:
    var: network3

- name: debug json
  debug:
    var: gateway 
