---
- name: Listen for chat message trigger-words
  hosts: localhost
  
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 443

  rules:
    - name: Webhook rule
      condition: true
      action:
        print_event:
          pretty: true

    - name: Send a chat message
      condition: true
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          post_events: true
          job_args:
            extra_vars:
              message: "Test Webhook"

    - name: Print event data
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
