---
- name: Listen for chat message trigger-words
  hosts: localhost
  
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 443

  rules:
    - name: Say hello
      condition: event.payload.message == "ansible"
      action:
        post_event:
          event:
            message: "Hello, {{ event.payload.message }}!  It is {{ lookup('pipe', 'date +%H:%M:%S') }}"

#    - name: Send a chat message
#      condition: event.message is defined
#      action:
#        run_job_template:
#          name: Demo Job Template
#          organization: Default
#          post_events: true
#          job_args:
#            extra_vars:
#              message: "{{ event.message }}"

    - name: Print event data
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
