---
- name: Listen for chat message trigger-words
  hosts: localhost
  
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  #  - name: Trigger a job
  #    condition: true
  #    action:
  #      run_job_template:
  #        name: Demo Job Template
  #        organization: Default
  #        post_events: true
  #        job_args:
  #          extra_vars:
  #            message: "Test Webhook"

    - name: Print event data
      condition: true
      action:
        print_event:
          pretty: true
